import "server-only";

export enum CookieName {
  GITHUB_OAUTH_STATE = "GITHUB_OAUTH_STATE",
  OAUTH_FLOW_TYPE = "OAUTH_FLOW_TYPE",
  GOOGLE_CODE_VERIFIER = "GOOGLE_CODE_VERIFIER",
  GOOGLE_OAUTH_STATE = "GOOGLE_OAUTH_STATE",
}
