import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import MyProvider from "./_providers/MyProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MyProvider>
      <html lang="en" className="dark">
        <body className={inter.className}>{children}</body>
      </html>
    </MyProvider>
  );
}
